package nl.marc.http_serve

enum class FileFormat(val extension: String, val mime: String, val fileType: FileType, val includeEncoding: Boolean = fileType == FileType.DOCUMENT) {
    AAC(".aac", "audio/aac", FileType.AUDIO),
    AVIF(".avif", "image/avif", FileType.IMAGE),
    AVI(".avi", "video/x-msvideo", FileType.VIDEO),
    BINARY(".bin", "application/octet-stream", FileType.BINARY),
    BMP(".bmp", "image/bmp", FileType.IMAGE),
    CSS(".css", "text/css", FileType.OTHER),
    CSV(".csv", "text/csv", FileType.DATA),
    EPUB(".epub", "application/epub+zip", FileType.DOCUMENT, false),
    GZIP(".gz", "application/gzip", FileType.BINARY),
    GIF(".gif", "image/gif", FileType.VIDEO),
    HMTL(".html", "text/html", FileType.DOCUMENT),
    ICON(".ico", "image/vnd.microsoft.icon", FileType.IMAGE),
    CALENDAR(".ics", "text/calendar", FileType.OTHER),
    JPG(".jpg", "image/jpeg", FileType.IMAGE),
    JPEG(".jpeg", "image/jpeg", FileType.IMAGE),
    JAVASCRIPT(".js", "text/javascript", FileType.OTHER),
    JSON(".json", "application/json", FileType.DATA),
    JSONLD(".jsonld", "application/ld+json", FileType.DATA),
    MIDI(".midi", "audio/midi", FileType.AUDIO),
    JAVASCRIPT_MODULE(".mjs", "text/javascript", FileType.OTHER),
    MP3(".mp3", "audio/mpeg", FileType.AUDIO),
    MP4(".mp4", "video/mp4", FileType.VIDEO),
    MPEG(".mpeg", "video/mpeg", FileType.VIDEO),
    OPENTYPE(".otf", "font/otf", FileType.FONT),
    PNG(".png", "image/png", FileType.IMAGE),
    PDF(".pdf", "application/pdf", FileType.DOCUMENT, false),
    RAR(".rar", "application/vnd.rar", FileType.BINARY),
    RTF(".rtf", "application/rtf", FileType.DOCUMENT),
    SVG(".svg", "image/svg+xml", FileType.IMAGE),
    TAR(".tar", "application/x-tar", FileType.BINARY),
    TRUETYPE(".ttf", "font/ttf", FileType.FONT),
    PLAIN_TEXT(".txt", "text/plain", FileType.DOCUMENT),
    WAV(".wav", "audio/wav", FileType.AUDIO),
    WEBM(".webm", "video/webm", FileType.VIDEO),
    WEBP(".webp", "image/webp", FileType.IMAGE),
    WOFF(".woff", "font/woff", FileType.FONT),
    WOFF2(".woff2", "font/woff2", FileType.FONT),
    XML(".xml", "application/xml", FileType.DATA),
    ZIP(".zip", "application/zip", FileType.BINARY),
    SEVEN_ZIP(".7z", "application/x-7z-compressed", FileType.BINARY);

    enum class FileType {
        AUDIO,
        VIDEO,
        IMAGE,
        DOCUMENT,
        DATA,
        BINARY,
        FONT,
        OTHER
    }
}
